#deploy without tag should fail early with msg

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,7 +19,10 @@ jobs:
       - name: Get tag
         run: |
           TAG=$(grep -Po '#deploy *\K\d+\.\d+' <<< "${{ github.event.head_commit.message }}")
-          [ -z "$TAG" ] && exit 1
+          if [ -z "$TAG" ]; then
+            echo "missing TAG"
+            exit 1
+          fi
           echo "TAG=$TAG" >> $GITHUB_ENV
 
       - name: Checkout
